openapi: 3.0.0
info:
  title: Course Management API
  description: API for managing courses in the system.
  version: 1.0.0
paths:
  /courses:
    get:
      summary: Retrieve all courses
      responses:
        '200':
          description: A list of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'

  /courses/search:
    get:
      summary: Search for courses with pagination
      parameters:
        - name: page
          in: query
          required: true
          description: Page number
          schema:
            type: integer
        - name: size
          in: query
          required: true
          description: Page size
          schema:
            type: integer
      responses:
        '200':
          description: A paginated list of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'

  /courses/{id}:
    get:
      summary: Retrieve a specific course by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the course
          schema:
            type: integer
      responses:
        '200':
          description: Course details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'

    put:
      summary: Update a specific course by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the course
          schema:
            type: integer
      requestBody:
        description: Updated course object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '200':
          description: Course updated successfully

    delete:
      summary: Delete a specific course by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the course
          schema:
            type: integer
      responses:
        '204':
          description: Course deleted successfully
        '404':
          description: Course not found

  /course:
    post:
      summary: Create a new course
      requestBody:
        description: Course object to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '201':
          description: Course created successfully

components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        starCourse:
          type: string
          format: date-time
        endCourse:
          type: string
          format: date-time
        presenceSheet:
          type: array
          items:
            $ref: '#/components/schemas/Student'
      required:
        - id
        - name
        - starCourse
        - endCourse
