openapi: 3.0.0
info:
  title: Justification Management API
  description: API for managing justifications for student absences.
  version: 1.0.0
paths:
  /justifications:
    get:
      summary: List of all justifications
      responses:
        '200':
          description: A list of justifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: true

  /justifications/search:
    get:
      summary: Search for justifications with pagination
      parameters:
        - name: page
          in: query
          required: true
          description: Page number
          schema:
            type: integer
        - name: size
          in: query
          required: true
          description: Page size
          schema:
            type: integer
      responses:
        '200':
          description: A paginated list of justifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: true

  /justification/{studentId}/{courseId}:
    get:
      summary: Retrieve a justification for a specific student and course
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student
          schema:
            type: string
        - name: courseId
          in: path
          required: true
          description: ID of the course
          schema:
            type: integer
      responses:
        '200':
          description: Justification details
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

    post:
      summary: Save a new justification
      requestBody:
        description: Justification object to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Justification'
        required: true
      responses:
        '201':
          description: Justification created successfully

    put:
      summary: Update an existing justification
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student
          schema:
            type: string
        - name: courseId
          in: path
          required: true
          description: ID of the course
          schema:
            type: integer
      requestBody:
        description: Updated justification object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Justification'
        required: true
      responses:
        '200':
          description: Justification updated successfully

    delete:
      summary: Delete a justification for a specific student and course
      parameters:
        - name: studentId
          in: path
          required: true
          description: ID of the student
          schema:
            type: string
        - name: courseId
          in: path
          required: true
          description: ID of the course
          schema:
            type: integer
      responses:
        '204':
          description: Justification deleted successfully
        '404':
          description: Justification not found

components:
  schemas:
    Justification:
      type: object
      properties:
        studentId:
          type: string
        courseId:
          type: integer
        type:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
      required:
        - studentId
        - courseId
        - type
        - description
        - date
