openapi: 3.0.0
info:
  title: Student Management API
  description: API for managing students in the system.
  version: 1.0.0
paths:
  /students:
    get:
      summary: Retrieve all students
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

  /students/search:
    get:
      summary: Search for students with pagination
      parameters:
        - name: page
          in: query
          required: true
          description: Page number
          schema:
            type: integer
        - name: size
          in: query
          required: true
          description: Page size
          schema:
            type: integer
      responses:
        '200':
          description: A paginated list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

  /students/{id}:
    get:
      summary: Retrieve a specific student by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the student
          schema:
            type: string
      responses:
        '200':
          description: Student details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'

    put:
      summary: Update a specific student by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the student
          schema:
            type: string
      requestBody:
        description: Updated student object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        '200':
          description: Student updated successfully

    delete:
      summary: Delete a specific student by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the student
          schema:
            type: string
      responses:
        '204':
          description: Student deleted successfully
        '404':
          description: Student not found

  /student:
    post:
      summary: Create a new student
      requestBody:
        description: Student object to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        '201':
          description: Student created successfully

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        contact:
          type: string
        universityYears:
          type: string
        genre:
          type: string
        status:
          type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - contact
        - universityYears
        - genre
        - status
